name: Missing Event
description: Request a Missing Event to be added
title: "[Event]: <name>"
labels: ["event-request"]
assignees:
  - yavko
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to write this event request!
  - type: input
    id: name
    attributes:
      label: What is the name of the event
      placeholder: Name
    validations:
      required: true
